included:
- ../PromisedRestfulSwift Sources
- ./PromisedRestfulSwift_Tests

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Frameworks
- Source/ExcludedFolder
- Source/ExcludedFile.swift
- build-framework.swift

cyclomatic_complexity: 12
file_length: 550
function_body_length: 80
function_parameter_count: 8
line_length: 200
type_body_length: 400
identifier_name:

disabled_rules:
#- valid_docs
- trailing_whitespace
#- nesting
#- type_name
#- identifier_name

custom_rules:
