use_frameworks!

platform :ios, '11.4'

target 'PromisedRestfulSwift_Example' do
  
  pod 'PromisedRestfulSwift', :path => '../'
  
  pod 'PromiseKit', '6.13.0'
  
  pod 'SwiftLint', '0.39.2'

  target 'PromisedRestfulSwift_Tests' do
    inherit! :search_paths

    
  end
end
