name: Release New Version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:

      # set xcode version
      - name: Set XCode Version
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - run: sudo xcode-select -s /Applications/Xcode_11.app

      # install dependencies
      - name: Install Dependencies
        run:                       |
            cd Example
            pod install --repo-update
        shell: bash

      # validate the library
      - name: Validate Library
        uses: ty0x2333/cocoapods-action@master
        with:
          workspace: Example/RestfulSWIFT.xcworkspace
          scheme: RestfulSWIFT-Example
          additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'

      # create the tag
      - name: Github Tag
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          tag_prefix: ""
          create_annotated_tag: true

      # Deploy to Cocoapod
      - name: Deploy to Cocoapod Action
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
