name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      
      # build the library
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      
      # run the tests
      - name: Run tests
        run: swift test -v
      
      # Validate through Cocoapod
      - name: CocoaPods Action
        uses: ty0x2333/cocoapods-action@0.2.0
      
      # create the tag
      - name: Github Tag
        uses: mathieudutour/github-tag-action@v4.1
        with:
          github_token: "610a6549c9920510c83fd327ec4aed38d476e8e8"
      
      # Deploy to Cocoapod
      # - name: Deploy to Cocoapod Action
      # uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.9
      # with:
      # # The Cocoapods Trunk Token
      #   COCOAPODS_TRUNK_TOKEN: 
